language: c++
dist: trusty

branches:
  except:
    - /^appveyor.*$/

git:
  depth: 10

matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        - GCC_VERSION=4.9
        - CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Release"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libsdl2-dev
            - libsdl2-net-dev
            - libogg-dev
            - libvorbis-dev
            - libghc-zlib-dev
            - autoconf
            - automake
            - libtool

    - os: linux
      compiler: gcc
      env:
        - GCC_VERSION=7
        - CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Debug"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libsdl2-dev
            - libsdl2-net-dev
            - libogg-dev
            - libvorbis-dev
            - libghc-zlib-dev
            - autoconf
            - automake
            - libtool
            
    - os: osx
      osx_image: xcode9.1
      env:
        # CMake has some issues locating SDL2 library installed by Homebrew 
        - CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Release -DSDL2_LIBRARY=/usr/local/lib/libSDL2.dylib"

before_install:  
#  - chmod +x ./quick_setup_scripts/install-sdl2-travis-ci.sh
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update;
      brew install sdl2_net libvorbis;
      ln -s /usr/local/bin/glibtoolize /usr/local/bin/libtoolize;
    fi
  - if [ -n "$GCC_VERSION" ]; then export CC="gcc-${GCC_VERSION}" CXX="g++-${GCC_VERSION}"; fi
  - if [ -n "$CLANG_VERSION" ]; then export CC="clang-${CLANG_VERSION}" CXX="clang++-${CLANG_VERSION}"; fi
  - $CC --version
  - $CXX --version

install: |
  if [[ "$HOST" == linux-* ]]; then
      docker exec bc apt update
      docker exec bc apt -y install git cmake zip wget libfuse2 build-essential libsdl2-dev libgl1-mesa-dev libopenal-dev libjpeg-dev libpng-dev libminizip-dev
#  else
#      cd ~
#      curl -O https://www.libsdl.org/release/SDL2-2.0.9.tar.gz
#      tar xzf SDL2-2.0.9.tar.gz
#      cd SDL2-2.0.9/
#      sed -i -e 's/@rpath//g' SDL.xcodeproj/project.pbxproj
#      xcodebuild -configuration Release
#      mkdir -p ~/Library/Frameworks/
#      ln -s `pwd`/build/Release/SDL2.framework ~/Library/Frameworks/
  fi

script:
  - echo ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd build
  - cmake ${CMAKE_OPTIONS} -DPK3_QUIET_ZIPDIR=YES ..
  - make -j2

notifications:
  email: false
