language: c++
dist: bionic

branches:
  except:
    - /^appveyor.*$/

git:
  depth: 10

matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        - GCC_VERSION=7
        - CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Release -DSDL2_INCLUDE_DIR=/libs/msvc/SDL2/include -DSDL2_LIBRARY=/usr/local/lib/libSDL2.so"
        
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libsdl2-dev
            - libsdl2-net-dev
            - libogg-dev
            - libvorbis-dev
            - libghc-zlib-dev
            - autoconf
            - automake
            - libtool
            - libphysfs-dev

    - os: linux
      compiler: gcc
      env:
        - GCC_VERSION=7
        - CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Debug -DSDL2_INCLUDE_DIR=/libs/msvc/SDL2/include -DSDL2_LIBRARY=/usr/local/lib/libSDL2.so"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libsdl2-dev
            - libsdl2-net-dev
            - libogg-dev
            - libvorbis-dev
            - libghc-zlib-dev
            - autoconf
            - automake
            - libtool
            - libphysfs-dev
            
    - os: osx
      osx_image: xcode10.1
      env:
        # CMake has some issues locating SDL2 library installed by Homebrew 
        - CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Release -DSDL2_INCLUDE_DIR=/usr/include/SDL2 -DSDL2_LIBRARY=/usr/local/lib/libSDL2.dylib"

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update;
      brew install sdl2_net libvorbis physfs;
      ln -s /usr/local/bin/glibtoolize /usr/local/bin/libtoolize;
    fi
  - if [ -n "$GCC_VERSION" ]; then export CC="gcc-${GCC_VERSION}" CXX="g++-${GCC_VERSION}"; fi
  - if [ -n "$CLANG_VERSION" ]; then export CC="clang-${CLANG_VERSION}" CXX="clang++-${CLANG_VERSION}"; fi
  - $CC --version
  - $CXX --version
  
script:
  - echo ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd build
  - cmake ${CMAKE_OPTIONS} -DPK3_QUIET_ZIPDIR=YES ..
  - make -j2

notifications:
  email: false
