#
# MiniLZO Win32 + MinGW MAKEFILE
#
# (Note: requires GNU make)
# 

BIN=liblzo.a

CC=mingw32-gcc.exe
CFLAGS=-Wall -O2 -fomit-frame-pointer -fno-strength-reduce

AR=ar r
RANLIB=ranlib

OBJS = minilzo.o    
    
# ----- TARGETS ------------------------------------------------------

all: $(BIN)

clean:
	rm -f $(OBJS) $(BIN) 
	
$(BIN): $(OBJS)
	$(AR) $(BIN) $(OBJS)
	$(RANLIB) $(BIN)
 
.PHONY: all clean

