#
# MiniLZO MacOS X MAKEFILE
#

BIN=liblzo.a

CC=gcc
RANLIB=ranlib
CFLAGS=-Wall -O2 -fomit-frame-pointer -fno-strength-reduce

OBJS=minilzo.o

# ----- TARGETS ------------------------------------------------------

all:    $(BIN)

clean:
	rm -f $(BIN) *.o

$(BIN): $(OBJS)
	libtool -static -o $(BIN) - $(OBJS)
	$(RANLIB) $(BIN)

.PHONY: all clean
