#
# SConscript (sub) file for MiniLZO
#
import os

Import('build_info')
Import('base_env')

env = base_env.Copy()

# extra optimisation
env.Append(CCFLAGS = ['-fomit-frame-pointer', '-fno-strength-reduce'])

env.StaticLibrary('lzo', ['minilzo.c'])

##--- editor settings ---
## vi:ts=4:sw=4:expandtab
