<!--- navigation menu --->

<div class="menus">

<ul>

<li><a href="http://edge.sourceforge.net/index.htm">Home</a>
<li><a href="about.htm">About</a>
<li><span class="notdone" hhref="screenshots.htm">Screenshots</span>

<li> <em>Download</em>
    <ul>
    <li><a href="http://sourceforge.net/project/showfiles.php?group_id=2232&amp;package_id=2188">Binaries</a>
    <li><a href="http://sourceforge.net/project/showfiles.php?group_id=2232&amp;package_id=6363">Source</a>
    <li><a href="http://sourceforge.net/project/showfiles.php?group_id=2232&amp;package_id=9196">Tools</a>
    <li><a href="http://sourceforge.net/project/showfiles.php?group_id=2232">All Files</a>
    </ul>
</li>

<li> <em>Documentation</em>
  <ul>
    <li><span class="notdone" hhref="README.txt">User Guide</span>
    <li><span class="notdone" hhref="tutorials.htm">Tutorials</span>
    <li><span class="notdone" hhref="ddf_online/index.htm">DDF Online</span>
    <li><a href="rts_online/start.htm">RTS Online</a>
    <li><span class="notdone" hhref="changelogs.htm">Changelogs</span>
    <li><a href="faq.htm">F.A.Q</a>
  </ul>
</li>

<li> <em>Sourceforge</em>
  <ul>
    <li><a href="http://sourceforge.net/projects/edge">Summary</a>
    <li><a href="http://sourceforge.net/forum/?group_id=2232">Forums</a>
    <li><a href="http://sourceforge.net/tracker/?group_id=2232&amp;atid=102232">Bugs</a>
    <li><a href="http://sourceforge.net/tracker/?group_id=2232&amp;atid=352232">Features</a>
  </ul>

<li><span class="notdone" hhref="projects.htm">Projects</span>
<li><a href="contact.htm">Contact</a>
<li><a href="credits.htm">Credits</a>

</ul>
</div>

