#
# SConscript (sub) file for Timidity
#
import os

Import('build_info')
Import('base_env')

env = base_env.Copy()

env.Append(CCFLAGS = ['-ffast-math'])

# allow #include "epi/xxxx.h" to find the correct file
env.Append(CPPPATH = ['#.'])

timid_sources = [
    'common.c', 'ctrlmode.c', 'filter.c', 'instrum.c',
    'mix.c', 'output.c', 'playmidi.c', 'readmidi.c',
    'resample.c', 'sdl_a.c', 'sdl_c.c',
    'tables.c', 'timidity.c']

env.StaticLibrary('timidity', timid_sources)

##--- editor settings ---
## vi:ts=4:sw=4:expandtab
