#
# SConscript (sub) file for DDF parser
#
import os

Import('build_info')
Import('main_env')

env = main_env.Copy()

# allow #include "epi/xxxx.h" to find the correct file
env.Append(CPPPATH = ['#.'])

#------- OBJECTS -----------------------------------

sources = [
    'anim.cc', 'attack.cc', 'boom.cc', 'colormap.cc',
    'font.cc', 'game.cc', 'image.cc', 'language.cc',
    'level.cc', 'line.cc', 'main.cc', 'playlist.cc',
    'sector.cc', 'sfx.cc', 'states.cc', 'style.cc',
    'switch.cc', 'thing.cc', 'weapon.cc',
    ] 

env.StaticLibrary('ddf', sources)

##--- editor settings ---
## vi:ts=4:sw=4:expandtab
