<!--- Footer --->

<div class="banner">

  <table width="100%" height="100%">
  <tr class="ft_row">
    <td align="left">&nbsp; &copy; 2006 The EDGE Team.</td>
	<td align="right">Hosted by&nbsp;

      <a HREF="http://sourceforge.net">
        <img src="http://sourceforge.net/sflogo.php?group_id=2232&amp;type=3" 
         width="125" height="37" alt="SourceForge.net" 
         align="MIDDLE" border="0" hspace="1">
      </a>
	  &nbsp;
    </td>
  </tr>
  </table>

</div>

