#
# SConscript (sub) file for Timidity
#
import os

Import('build_info')
Import('base_env')

env = base_env.Copy()

env.Append(CCFLAGS = ['-ffast-math'])

# allow #include "epi/xxxx.h" to find the correct file
env.Append(CPPPATH = ['#.'])

timid_sources = [
    'common.cc', 'filter.cc', 'instrum.cc',
    'mix.cc', 'output.cc', 'playmidi.cc', 'loadmidi.cc',
    'resample.cc', 'dummy.cc', 'tables.cc', 'timidity.cc']

env.StaticLibrary('timidity', timid_sources)

##--- editor settings ---
## vi:ts=4:sw=4:expandtab
