<!--- Editing menu --->

<div class="menus">

<ul>

<li><a href="http://edge.sourceforge.net/index.html">EDGE Home</a>
<li>&nbsp;

<li> <em>Editing Guide</em>
<ul>
    <li> <a href="overview.htm">Overview</a>
    <li> <a href="line_types.htm">Line types</a>
    <li> <a href="sec_types.htm">Sector types</a>
</ul>

<li>&nbsp;

<li> <em>Specifications</em>
<ul>
    <li> <a href="doom_specs.htm">Doom Specs</a>
    <li> <a href="boom_ref.htm">Boom Editing</a>
    <li> <a href="JointTextureSpec.htm">Joint Texture</a>
</ul>

</ul>
</div>

