<!--- Screenshot mini-menu --->

<div>
  <table class="shots_menu" xxxwidth="100%" align="center">
  <tr>
    <td>
	  <if prev> <a href="${prev}.htm">Previous</a>
	  <else> &nbsp;
	  </if>
	  </td>
    <td>
	  <a href="http://edge.sourceforge.net/screenshots.htm">Contents</a>
	  </td>
    <td>
	  <if next> <a href="${next}.htm">Next</a>
	  <else> &nbsp;
	  </if>
	  </td>
  </tr>
  </table>
</div>

