//------------------------------------------------------------------------
//  SYSTEM : Bridging code
//------------------------------------------------------------------------
// 
//  DEH_EDGE  Copyright (C) 2004  The EDGE Team
// 
//  This program is under the GNU General Public License.
//  It comes WITHOUT ANY WARRANTY of any kind.
//  See COPYING.txt for the full details.
//
//------------------------------------------------------------------------

#ifndef __SYSTEM_HDR__
#define __SYSTEM_HDR__


#define VERSION  "1.0"

#define GEN_BY_COMMENT  "// Generated by DEH_EDGE v" VERSION "\n\n"

#define F_FIXED(n)  ((float)(n) / 65536.0)


void System_Startup(void);
void System_Shutdown(void);

extern int target_version;  // decimal, e.g. 128

extern bool quiet_mode;
extern bool all_mode;

// text output functions
void PrintMsg(const char *str, ...);
void PrintWarn(const char *str, ...);
void FatalError(const char *str, ...);
void InternalError(const char *str, ...);

void ShowProgress(int count, int limit);
void ClearProgress(void);

// endian handling
unsigned short Endian_U16(unsigned short);
unsigned int   Endian_U32(unsigned int);

// these are only used for debugging
void Debug_PrintMsg(const char *str, ...);


#endif /* __SYSTEM_HDR__ */
