#
# SConscript (sub) file for the EPI
#
import os

Import('build_info')
Import('env')

env.Append(CCFLAGS = ['-ffast-math'])

epi_sources = [
    'arrays.cc', 'bytearray.cc', 'exe_path.cc',
    'file.cc', 'filesystem.cc', 'file_memory.cc', 'file_sub.cc',
    'image_data.cc', 'image_hq2x.cc',
    'image_jpeg.cc', 'image_png.cc', 'image_tga.cc',
    'math_angle.cc', 'math_bbox.cc', 'math_color.cc',
    'math_crc.cc', 'math_md5.cc', 'math_oddity.cc',
    'math_matrix.cc', 'math_vector.cc',
    'math_random.cc', 'mersenne_twist.cc',
    'mus_2_midi.cc',
    'path.cc', 'str_format.cc',
    'sound_data.cc', 'sound_gather.cc', 'sound_wav.cc',
    'timestamp.cc', 'utility.cc']

# operating system specifics
if build_info['platform'] == "win32":
    epi_sources += ['epi_win32.cc', 'filesystem_win32.cc']

else: # linux
    epi_sources += ['epi_linux.cc', 'filesystem_linux.cc']

env.StaticLibrary('epi', epi_sources)

##--- editor settings ---
## vi:ts=4:sw=4:expandtab
