#ifndef __I_CTRL__
#define __I_CTRL__

#if SDL_VERSION_ATLEAST(2, 0, 0)
#define KEYBOARD_0 SDLK_KP_0
#define KEYBOARD_1 SDLK_KP_1
#define KEYBOARD_2 SDLK_KP_2
#define KEYBOARD_3 SDLK_KP_3
#define KEYBOARD_4 SDLK_KP_4
#define KEYBOARD_5 SDLK_KP_5
#define KEYBOARD_6 SDLK_KP_6
#define KEYBOARD_7 SDLK_KP_7
#define KEYBOARD_8 SDLK_KP_8
#define KEYBOARD_9 SDLK_KP_9
#define KEYBOARD_PRINTSCREEN SDLK_PRINTSCREEN
#define KEYBOARD_NUMLOCKCLEAR SDLK_NUMLOCKCLEAR
#define KEYBOARD_SCROLLLOCK SDLK_SCROLLLOCK
#define KEYBOARD_LGUI SDLK_LGUI
#define KEYBOARD_RGUI SDLK_RGUI
#define GET_JOYSTICK_NAME SDL_JoystickNameForIndex
#else
#define KEYBOARD_0 SDLK_KP0
#define KEYBOARD_1 SDLK_KP1
#define KEYBOARD_2 SDLK_KP2
#define KEYBOARD_3 SDLK_KP3
#define KEYBOARD_4 SDLK_KP4
#define KEYBOARD_5 SDLK_KP5
#define KEYBOARD_6 SDLK_KP6
#define KEYBOARD_7 SDLK_KP7
#define KEYBOARD_8 SDLK_KP8
#define KEYBOARD_9 SDLK_KP9
#define KEYBOARD_PRINTSCREEN SDLK_PRINT
#define KEYBOARD_NUMLOCKCLEAR SDLK_NUMLOCK
#define KEYBOARD_SCROLLLOCK SDLK_SCROLLOCK
#define KEYBOARD_LGUI -601
#define KEYBOARD_RGUI -600
#define GET_JOYSTICK_NAME SDL_JoystickName
#endif

#endif  /* __I_CTRL__ */
