#
# SConscript (sub) file for EDGE engine
#
import os

Import('build_info')
Import('main_env')

env = main_env.Copy()

env.Append(CCFLAGS = ['-ffast-math'])

# allow #include "epi/xxxx.h" to find the correct file
env.Append(CPPPATH = ['#.'])

if 1: # not build_info['release']:
  env.Append(CCFLAGS = ['-DDEVELOPERS'])

#------- OBJECTS -----------------------------------

sources_1 = [
    'i_main.cc',
    'i_cd.cc',  'i_ctrl.cc', 'i_video.cc',
    'i_sound.cc',
    'am_map.cc', 'con_con.cc', 'con_cvar.cc', 'con_main.cc', 'ddf_anim.cc',
    'ddf_atk.cc', 'ddf_boom.cc', 'ddf_colm.cc', 'ddf_font.cc', 
    'ddf_game.cc', 'ddf_image.cc', 'ddf_lang.cc', 'ddf_levl.cc', 
    'ddf_line.cc', 'ddf_main.cc', 'ddf_mobj.cc', 'ddf_mus.cc', 
    'ddf_sect.cc', 'ddf_sfx.cc', 'ddf_stat.cc', 'ddf_style.cc', 
    'ddf_swth.cc', 'ddf_weap.cc', 'dem_chunk.cc', 'dem_glob.cc', 
    'dm_defs.cc', 'dm_state.cc', 'e_demo.cc', 'e_input.cc', 'e_main.cc', 
    'e_player.cc', 'f_finale.cc', 'g_game.cc', 'gui_ctls.cc', 'gui_main.cc', 
    'hu_font.cc', 'hu_lib.cc', 'hu_stuff.cc', 'hu_style.cc',
    'i_asm.cc' ] 

sources_2 = [
    'l_glbsp.cc',
    'l_deh.cc', 'lu_gamma.cc', 'm_argv.cc', 'm_bbox.cc', 
    'm_cheat.cc', 'm_math.cc', 'm_menu.cc', 'm_misc.cc', 'm_option.cc', 
    'm_netgame.cc', 'm_random.cc', 'mus_2_midi.cc',
    'n_network.cc', 'n_packet.cc', 'protocol.cc',
    'p_action.cc', 'p_bot.cc', 'p_enemy.cc', 'p_inter.cc', 'p_lights.cc', 
    'p_map.cc', 'p_maputl.cc', 'p_mobj.cc', 'p_plane.cc', 'p_setup.cc', 
    'p_sight.cc', 'p_spec.cc', 'p_switch.cc', 'p_tick.cc', 'p_user.cc', 
    'p_forces.cc', 'p_telept.cc', 'p_weapon.cc',
    'r2_util.cc', 'rad_act.cc', 'rad_pars.cc', 'rad_trig.cc', 
    'r_bsp.cc', 'r_data.cc', 'rgl_bsp.cc', 'rgl_fx.cc', 'rgl_main.cc', 
    'rgl_occ.cc', 'rgl_sky.cc', 'rgl_tex.cc', 'rgl_thing.cc', 'rgl_unit.cc', 
    'rgl_wipe.cc', 'r_layers.cc', 'r_main.cc', 'r_sky.cc', 'r_things.cc', 
    'r_vbinit.cc', 'r_view.cc', 's_blit.cc', 's_cache.cc', 's_music.cc', 'st_lib.cc', 
    'st_stuff.cc', 'sv_chunk.cc', 'sv_dump.cc', 'sv_glob.cc', 'sv_level.cc', 
    'sv_load.cc', 'sv_main.cc', 'sv_misc.cc', 'sv_mobj.cc', 'sv_play.cc', 
    'sv_save.cc', 'v_colour.cc', 'v_res.cc', 'w_image.cc', 'wi_stuff.cc', 
    'wp_wipe.cc', 'w_textur.cc', 'w_wad.cc', 'z_zone.cc', 
    ]

# operating system specifics
if build_info['platform'] == "win32":
    sources_3 = ['w32_cd.cc', 'w32_compen.cc',
        'w32_music.cc',
        'w32_mus.cc', 'w32_net.cc',
                        'w32_system.cc']
else: # linux
    sources_3 = ['unx_compen.cc', 'unx_music.cc', 
        'unx_net.cc',                 'unx_system.cc']

# another HACK (stupid linker!)
# sources_3 += ['oggplayer.cc'] 
# sources_1 += ['humdinger.cc'] 

env.StaticLibrary('edge1', sources_1 + sources_2 + sources_3)

##--- editor settings ---
## vi:ts=4:sw=4:expandtab
