# - Find physfs
# Find the native physfs includes and library


IF (PHYSFS_INCLUDE_DIR AND PHYSFS_LIBRARIES)
  # Already in cache, be silent
  SET(PHYSFS_FIND_QUIETLY TRUE)
ENDIF (PHYSFS_INCLUDE_DIR AND PHYSFS_LIBRARIES)

FIND_PATH(PHYSFS_INCLUDE_DIR physfs.h)

FIND_LIBRARY(PHYSFS_LIBRARIES NAMES physfs )
MARK_AS_ADVANCED( PHYSFS_LIBRARIES PHYSFS_INCLUDE_DIR )

# handle the QUIETLY and REQUIRED arguments and set PHYSFS_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(physfs DEFAULT_MSG PHYSFS_LIBRARIES PHYSFS_INCLUDE_DIR)


