#
# SConscript for Lee Salzman's ENET library
#
import os

Import('build_info')
Import('env')

enet_sources = [
	'callbacks.c', 'host.c', 'list.c',
	'packet.c', 'peer.c', 'protocol.c',
	'unix.c', 'win32.c']

env.StaticLibrary('enet', enet_sources)

##--- editor settings ---
## vi:ts=4:sw=4:expandtab
