//----------------------------------------------------------------------------
//  EDGE Input handling
//----------------------------------------------------------------------------
// 
//  Copyright (c) 1999-2009  The EDGE Team.
// 
//  This program is free software; you can redistribute it and/or
//  modify it under the terms of the GNU General Public License
//  as published by the Free Software Foundation; either version 2
//  of the License, or (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//----------------------------------------------------------------------------
//
//  Based on the DOOM source code, released by Id Software under the
//  following copyright:
//
//    Copyright (C) 1993-1996 by id Software, Inc.
//
//----------------------------------------------------------------------------
//
// -MH- 1998/07/02 Added key_flyup and key_flydown variables (no logic yet)
// -MH- 1998/08/18 Flyup and flydown logic
//

#include "i_defs.h"

#include "ddf/level.h"

#include "dm_defs.h"
#include "dm_state.h"
#include "e_event.h"
#include "e_input.h"
#include "e_main.h"
#include "g_game.h"
#include "hu_stuff.h"
#include "m_math.h"
#include "m_misc.h"
#include "r_misc.h"
#include "z_zone.h"


extern bool CON_Responder(event_t *ev);
extern bool   M_Responder(event_t *ev);
extern bool   G_Responder(event_t *ev);

//
// EVENT HANDLING
//
// Events are asynchronous inputs generally generated by the game user.
// Events can be discarded if no responder claims them
//
#define MAXEVENTS  128

static event_t events[MAXEVENTS];
static int eventhead;
static int eventtail;

//
// controls (have defaults) 
// 
key_binding_c key_forward;
key_binding_c key_backward;
key_binding_c key_strafeleft;
key_binding_c key_straferight;

key_binding_c key_right;
key_binding_c key_left;
key_binding_c key_lookup;
key_binding_c key_lookdown;
key_binding_c key_lookcenter;

// -ES- 1999/03/28 Zoom Key
key_binding_c key_zoom;

key_binding_c key_fire;
key_binding_c key_secondatk;
key_binding_c key_use;
key_binding_c key_strafe;
key_binding_c key_speed;
key_binding_c key_autorun;
key_binding_c key_nextweapon;
key_binding_c key_prevweapon;
key_binding_c key_map;
key_binding_c key_180;
key_binding_c key_talk;
key_binding_c key_console;
key_binding_c key_mlook;
key_binding_c key_reload;

// -MH- 1998/07/10 Flying keys
key_binding_c key_flyup;
key_binding_c key_flydown;

#define MAXPLMOVE  (forwardmove[1])

static int forwardmove[2] = {0x19, 0x32};
static int sidemove[2]    = {0x18, 0x28};
static int upwardmove[2]  = {0x19, 0x32};  // -MH- 1998/08/18 Up/Down movement
static int angleturn[3]   = {640, 1280, 320};  // + slow turn 

#define ZOOM_ANGLE_DIV  3

#define SLOWTURNTICS    6

#define GK_DOWN  0x01
#define GK_UP    0x02

byte gamekeydown[NUMKEYS];

static int turnheld;   // for accelerative turning 
static int mlookheld;  // for accelerative mlooking 

// toggled by autorun button.
cvar_c in_autorun;
cvar_c in_stageturn;
cvar_c in_shiftlook;

//-------------------------------------------
// -KM-  1998/09/01 Analogue binding
// -ACB- 1998/09/06 Two-stage turning switch
//

// The last one is ignored (AXIS_DISABLE)
static float analogue[6] = {0, 0, 0, 0, 0, 0};


bool E_InputCheckKey(int keynum)
{
#ifdef DEVELOPERS
	if ((keynum >> 16) > NUMKEYS)
		I_Error("Invalid key!");
	else if ((keynum & 0xffff) > NUMKEYS)
		I_Error("Invalid key!");
#endif

	if (gamekeydown[keynum >> 16] & GK_DOWN)
		return true;
	else if (gamekeydown[keynum & 0xffff] & GK_DOWN)
		return true;
	else
		return false;
}

#if 0  // UNUSED ???
static int CmdChecksum(ticcmd_t * cmd)
{
	int i;
	int sum = 0;

	for (i = 0; i < (int)sizeof(ticcmd_t) / 4 - 1; i++)
		sum += ((int *)cmd)[i];

	return sum;
}
#endif

//
// E_BuildTiccmd
//
// Builds a ticcmd from all of the available inputs
//
// -ACB- 1998/07/02 Added Vertical angle checking for mlook.
// -ACB- 1998/07/10 Reformatted: I can read the code! :)
//

static bool allow180 = true;
static bool allowzoom = true;
static bool allowautorun = true;

void E_BuildTiccmd(ticcmd_t * cmd)
{
	Z_Clear(cmd, ticcmd_t, 1);

	bool strafe = key_strafe.IsPressed();
	int speed   = key_speed.IsPressed() ? 1 : 0;

	if (in_autorun.d)
		speed = !speed;

	float forward = 0;
	float upward = 0;  // -MH- 1998/08/18 Fly Up/Down movement
	float side = 0;

	if (key_right.IsPressed() || key_left.IsPressed())
		turnheld++;
	else
		turnheld = 0;

	if (key_lookup.IsPressed() || key_lookdown.IsPressed())
		mlookheld++;
	else
		mlookheld = 0;

	int t_speed = speed;
	int u_speed = speed;

	if (in_stageturn.d)
	{
		// slow turn ?
		if (turnheld < SLOWTURNTICS)
			t_speed = 2;

		// slow turn ?
		if (mlookheld < SLOWTURNTICS)
			u_speed = 2;
	}

	int m_speed = in_shiftlook.d ? speed : 0;

	// -ES- 1999/03/28 Zoom Key
	if (key_zoom.IsPressed())
	{
		if (allowzoom)
		{
			cmd->extbuttons |= EBT_ZOOM;
			allowzoom = false;
		}
	}
	else
		allowzoom = true;

	// -AJA- 2000/04/14: Autorun toggle
	if (key_autorun.IsPressed())
	{
		if (allowautorun)
		{
			in_autorun = in_autorun.d ? 0 : 1;
			allowautorun = false;
		}
	}
	else
		allowautorun = true;

	// You have to release the 180 deg turn key before you can press it again
	if (key_180.IsPressed())
	{
		if (allow180)
			cmd->angleturn = ANG180 >> 16;
		allow180 = false;
	}
	else
	{
		allow180 = true;
		cmd->angleturn = 0;
	}

	//let movement keys cancel each other out
	if (strafe)
	{
		if (key_right.IsPressed())
			side += sidemove[speed];

		if (key_left.IsPressed())
			side -= sidemove[speed];

		// -KM- 1998/09/01 Analogue binding
		// -ACB- 1998/09/06 Side Move Speed Control
		side += analogue[AXIS_TURN] * sidemove[speed] / 64.0;
	}
	else
	{
		int angle_rate = angleturn[t_speed];

		if (view_zoom > 0)
			angle_rate /= ZOOM_ANGLE_DIV;

		if (key_right.IsPressed())
			cmd->angleturn -= angle_rate;

		if (key_left.IsPressed())
			cmd->angleturn += angle_rate;

		// -KM- 1998/09/01 Analogue binding
		// -ACB- 1998/09/06 Angle Turn Speed Control
		cmd->angleturn -= analogue[AXIS_TURN] * angleturn[m_speed] / 64.0;
	}

	cmd->mlookturn = 0;

	if (g_mlook.d && !(map_features & MPF_NoMLook))
	{
		int mlook_rate = angleturn[u_speed] / 2;

		if (view_zoom > 0)
			mlook_rate /= ZOOM_ANGLE_DIV;

		// -ACB- 1998/07/02 Use VertAngle for Look/up down.
		if (key_lookup.IsPressed())
			cmd->mlookturn += mlook_rate;

		// -ACB- 1998/07/02 Use VertAngle for Look/up down.
		if (key_lookdown.IsPressed())
			cmd->mlookturn -= mlook_rate;

		// -ACB- 1998/07/02 Use CENTER flag to center the vertical look.
		if (key_lookcenter.IsPressed())
			cmd->extbuttons |= EBT_CENTER;

		// -KM- 1998/09/01 More analogue binding
		cmd->mlookturn += analogue[AXIS_MLOOK] * angleturn[m_speed] / 64.0f;
	}

	// -MH- 1998/08/18 Fly up
	if (g_true3d.d && !(map_features & MPF_NoTrue3D))
	{
		if ((key_flyup.IsPressed()))
			upward += upwardmove[speed];

		// -MH- 1998/08/18 Fly down
		if ((key_flydown.IsPressed()))
			upward -= upwardmove[speed];

		upward += analogue[AXIS_FLY] * upwardmove[speed] / 64.0;
	}

	if (key_forward.IsPressed())
		forward += forwardmove[speed];

	if (key_backward.IsPressed())
		forward -= forwardmove[speed];

	// -KM- 1998/09/01 Analogue binding
	// -ACB- 1998/09/06 Forward Move Speed Control
	forward += analogue[AXIS_FORWARD] * forwardmove[speed] / 64.0;

	// -ACB- 1998/09/06 Side Move Speed Control
	side += analogue[AXIS_STRAFE] * sidemove[speed] / 64.0;

	if (key_straferight.IsPressed())
		side += sidemove[speed];

	if (key_strafeleft.IsPressed())
		side -= sidemove[speed];

	// buttons
	cmd->chatchar = HU_DequeueChatChar();

	if (key_fire.IsPressed())
		cmd->buttons |= BT_ATTACK;

	if (key_use.IsPressed())
		cmd->buttons |= BT_USE;

	if (key_secondatk.IsPressed())
		cmd->extbuttons |= EBT_SECONDATK;

	if (key_reload.IsPressed())
		cmd->extbuttons |= EBT_RELOAD;

	// -KM- 1998/11/25 Weapon change key
	for (int w = 0; w < WEAPON_KEYS; w++)
	{
		if (E_InputCheckKey('0' + w))
		{
			cmd->buttons |= BT_CHANGE;
			cmd->buttons |= w << BT_WEAPONSHIFT;
			break;
		}
	}

	if (key_nextweapon.IsPressed())
	{
		cmd->buttons |= BT_CHANGE;
		cmd->buttons |= (BT_NEXT_WEAPON << BT_WEAPONSHIFT);
	}
	else if (key_prevweapon.IsPressed())
	{
		cmd->buttons |= BT_CHANGE;
		cmd->buttons |= (BT_PREV_WEAPON << BT_WEAPONSHIFT);
	}

	// -MH- 1998/08/18 Yep. More flying controls...
	forward = CLAMP(-MAXPLMOVE, forward, MAXPLMOVE);
	 upward = CLAMP(-MAXPLMOVE,  upward, MAXPLMOVE);
	   side = CLAMP(-MAXPLMOVE,    side, MAXPLMOVE);

	cmd->forwardmove += I_ROUND(forward);
	cmd->sidemove    += I_ROUND(side);
	cmd->upwardmove  += I_ROUND(upward);

	// -KM- 1998/09/01 Analogue binding
	for (int k = 0; k < 6; k++)
		analogue[k] = 0;
}

//
// Get info needed to make ticcmd_ts for the players.
// 
bool INP_Responder(event_t * ev)
{
	switch (ev->type)
	{
		case ev_keydown:
			if (ev->value.key.sym != KEYD_IGNORE &&
			    ev->value.key.sym < NUMKEYS)
			{
				gamekeydown[ev->value.key.sym] &= ~GK_UP;
				gamekeydown[ev->value.key.sym] |=  GK_DOWN;
			}

			// eat key down events 
			return true;

		case ev_keyup:
			if (ev->value.key.sym != KEYD_IGNORE &&
			    ev->value.key.sym < NUMKEYS)
			{
				gamekeydown[ev->value.key.sym] |= GK_UP;
			}

			// always let key up events filter down 
			return false;

			// -KM- 1998/09/01 Change mouse/joystick to analogue
		case ev_analogue:
			{
				// -AJA- 1999/07/27: Mlook key like quake's.
				if ((g_mlook.d && !(map_features & MPF_NoMLook)) &&
				    key_mlook.IsPressed())
				{
					if (ev->value.analogue.axis == mouse_xaxis.d)
					{
						analogue[AXIS_TURN] += ev->value.analogue.amount;
						return true;
					}
					if (ev->value.analogue.axis == mouse_yaxis.d)
					{
						analogue[AXIS_MLOOK] += ev->value.analogue.amount;
						return true;
					}
				}

				analogue[ev->value.analogue.axis] += ev->value.analogue.amount;
				return true;  // eat events
			}

		default:
			break;
	}

	return false;
}

//
// Sets the turbo scale (100 is normal)
//
void E_SetTurboScale(int scale)
{
	const int origforwardmove[2] = {0x19, 0x32};
	const int origsidemove[2]    = {0x18, 0x28};
	const int origupwardmove[2]  = {0x19, 0x32};

	forwardmove[0] = origforwardmove[0] * scale / 100;
	forwardmove[1] = origforwardmove[1] * scale / 100;
	sidemove[0]    = origsidemove[0] * scale / 100;
	sidemove[1]    = origsidemove[1] * scale / 100;
	upwardmove[0]  = origupwardmove[0] * scale / 100;
	upwardmove[1]  = origupwardmove[1] * scale / 100;
}


void E_ClearInput(void)
{
	Z_Clear(gamekeydown, byte, NUMKEYS);

	for (int k = 0; k < 6; k++)
		analogue[k] = 0;

	turnheld  = 0;
	mlookheld = 0;
}

//
// Finds all keys in the gamekeydown[] array which have been released
// and clears them.  The value is NOT cleared by INP_Responder() since
// that prevents very fast presses (also the mousewheel) from being
// down long enough to be noticed by E_BuildTiccmd().
//
// -AJA- 2005/02/17: added this.
//
void E_UpdateKeyState(void)
{
	for (int k = 0; k < NUMKEYS; k++)
		if (gamekeydown[k] & GK_UP)
			gamekeydown[k] = 0;
}

//
// Generate events which should release all current keys.
//
void E_ReleaseAllKeys(void)
{
	int i;
	for (i = 0; i < NUMKEYS; i++)
	{
		if (gamekeydown[i] & GK_DOWN)
		{
			event_t ev;
			
			ev.type = ev_keyup;
			ev.value.key.sym = i;
			ev.value.key.unicode = 0;
			
			E_PostEvent(&ev);
		}
	}
}

//
// Called by the I/O functions when input is detected
//
void E_PostEvent(event_t * ev)
{
	events[eventhead] = *ev;
	eventhead = (eventhead + 1) % MAXEVENTS;

#ifdef DEBUG_KEY_EV  //!!!!
if (ev->type == ev_keydown || ev->type == ev_keyup)
{
	L_WriteDebug("EVENT @ %08x %d %s\n",
		I_ReadMicroSeconds()/1000,
		ev->value.key.sym,
		(ev->type == ev_keyup) ? "DOWN" : "up");
}
#endif
}

//
// Send all the events of the given timestamp down the responder chain
//
void E_ProcessEvents(void)
{
	event_t *ev;

	for (; eventtail != eventhead; eventtail = (eventtail + 1) % MAXEVENTS)
	{
		ev = &events[eventtail];

		if (chat_on && HU_Responder(ev))
			continue;  // let chat eat the event first of all

		if (CON_Responder(ev))
			continue;  // GUI ate the event

		if (M_Responder(ev))
			continue;  // menu ate the event

		G_Responder(ev);  // let game eat it, nobody else wanted it
	}
}


//--- editor settings ---
// vi:ts=4:sw=4:noexpandtab
