#
# SConscript (sub) file for EDGE engine
#
import os

Import('build_info')
Import('main_env')

env = main_env.Copy()

env.Append(CCFLAGS = ['-ffast-math'])

# allow #include "epi/xxxx.h" to find the correct file
env.Append(CPPPATH = ['#.'])

if 1: # not build_info['release']:
    env.Append(CCFLAGS = ['-DDEVELOPERS'])

#------- OBJECTS -----------------------------------

sources = [
    'i_main.cc',  'i_ctrl.cc', 'i_video.cc',
    'i_sound.cc', 'i_net.cc',
    'con_con.cc', 'con_cvar.cc', 'con_main.cc',
    'dem_chunk.cc', 'dem_glob.cc', 
    'e_demo.cc', 'e_input.cc', 'e_main.cc', 
    'e_player.cc', 'f_finale.cc', 'g_game.cc',
    'hu_font.cc', 'hu_lib.cc', 'hu_stuff.cc', 'hu_style.cc',
    'l_glbsp.cc',
    'l_deh.cc', 'm_argv.cc', 'm_bbox.cc', 
    'm_cheat.cc', 'm_math.cc', 'm_menu.cc', 'm_misc.cc', 'm_option.cc', 
    'm_netgame.cc', 'm_random.cc', 'mus_2_midi.cc',
    'n_bcast.cc', 'n_reliable.cc',
    'n_network.cc', 'n_packet.cc', 'n_protocol.cc',
    'p_action.cc', 'p_bot.cc', 'p_enemy.cc', 'p_inter.cc', 'p_lights.cc', 
    'p_map.cc', 'p_maputl.cc', 'p_mobj.cc', 'p_plane.cc', 'p_setup.cc', 
    'p_sight.cc', 'p_spec.cc', 'p_switch.cc', 'p_tick.cc', 'p_user.cc', 
    'p_forces.cc', 'p_telept.cc', 'p_weapon.cc',
    'rad_act.cc', 'rad_pars.cc', 'rad_trig.cc', 
    'r_automap.cc', 'r_draw.cc', 'r_shader.cc',
    'r_render.cc', 'r_effects.cc', 'r_main.cc',
    'r_occlude.cc', 'm_logo.cc', 'r_things.cc', 'r_units.cc', 
    'r_wipe.cc', 'r_misc.cc', 'r_sky.cc',
    'r_vbinit.cc', 'r_view.cc',
    's_blit.cc', 's_cache.cc', 's_sound.cc',
    's_music.cc', 's_ogg.cc', 'st_lib.cc', 'st_stuff.cc',
    'sv_chunk.cc', 'sv_dump.cc', 'sv_glob.cc', 'sv_level.cc', 
    'sv_load.cc', 'sv_main.cc', 'sv_misc.cc', 'sv_mobj.cc', 'sv_play.cc', 
    'sv_save.cc', 'r_colors.cc', 'r_modes.cc', 'r_md2.cc',
    'r_image.cc', 'r_doomtex.cc', 'r_texgl.cc', 'f_stats.cc', 
    'w_flat.cc', 'w_model.cc', 'w_sprite.cc',
    'w_texture.cc', 'w_wad.cc', 'z_zone.cc', 
    ]

if 0:
    sources = sources + [
    'wf_util.cc', 'wf_colors.cc', 'wf_maps.cc',
#    'wf_setup.cc'
    ]

# operating system specifics
if build_info['platform'] == "win32":
    sources_3 = ['w32_cd.cc',
        'w32_music.cc', 'w32_mus.cc',
        'w32_net.cc', 'w32_system.cc']

else: # linux
    sources_3 = ['i_cd.cc', 'unx_music.cc', 
        'unx_net.cc', 'unx_system.cc']

# another HACK (stupid linker!)
# sources_3 += ['s_ogg.cc'] 
# sources_1 += ['s_humid.cc'] 

env.StaticLibrary('edge1', sources + sources_3)

##--- editor settings ---
## vi:ts=4:sw=4:expandtab
